/**
 * Generate static-assets.js from client/dist
 * Reads HTML, CSS, JS and exports them as string constants
 */
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const root = join(__dirname, '..');
const dist = join(root, 'client/dist');
const html = readFileSync(join(dist, 'index.html'), 'utf8');
const css = readFileSync(join(dist, 'assets/index.css'), 'utf8');
const js = readFileSync(join(dist, 'assets/index.js'), 'utf8');

const output = `// AUTO-GENERATED by scripts/gen-assets.mjs — do not edit
export const ASSET_HTML = ${JSON.stringify(html)};
export const ASSET_CSS = ${JSON.stringify(css)};
export const ASSET_JS = ${JSON.stringify(js)};
`;

writeFileSync(join(root, 'src/static-assets.js'), output);
console.log(`✓ Generated src/static-assets.js (${(html.length + css.length + js.length / 1024).toFixed(0)}KB)`);
